### ISSUE TITLE
Support for standard suits?

### ISSUE THREAD

**Issue by Paradox75831004** [TheRealCanad1an/Lethal-company-better-player-model-mod#2]
Will there be support for standard suits? (green, yellow, pajama)
At least to start with, and in the future, give them a tool for updating costumes on this beautiful HD model.

**Comment by Paradox75831004** [comment]
+ it seems to me that the lighting somehow doesn’t work as well on the HD model, but maybe it’s just me

**Comment by TheRealCanad1an** [comment]
I only have time to fix bugs on this mod, sorry.
