### ISSUE TITLE
Floating Textures at The Company

### ISSUE THREAD

**Issue by murdocksblock** [TheRealCanad1an/Lethal-company-better-player-model-mod#6]
Just to the right of your ship at The Company, a floating plane with the HD suit texture on it is floating in the map. Additionally, and somewhat unrelated, this mod doesn't have official viewmodel support, and generating it via the replacement config leads to holes in the arm mesh.

**Comment by murdocksblock** [comment]
@TheRealCanad1an

**Comment by TheRealCanad1an** [comment]
Sorry for the late response, I have been hella busy. I'm looking into this now.

**Comment by TheRealCanad1an** [comment]
Fixed. It was due to how I loaded the textures, I set there scale to 0 because turning the sprite renderer off didn't want to work.
